title: Jan Taverniers
description: >-
  This is Jan Taverniers' portofolio. You will find in there his projects and his curriculum. There are also some hints about his favorite beverage and how to have one with him.
baseurl: "/"
url: "https://gabrieltach.github.io"
lang: en_US
author:
  twitter: JanTaverniers

twitter:
  username: JanTaverniers
  card: summary

github_username:  gabrielTach

social:
  name: Jan Taverniers
  links:
    - https://twitter.com/JanTaverniers
    - https://www.linkedin.com/in/jan-taverniers/
    - https://github.com/gabrielTach

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  projects:
    output: true
